dist: trusty
language: java
sudo: false
jdk: oraclejdk8
install: true
addons:
  sonarcloud:
    organization: "joseph-org"
    token:
      secure: "**************************"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache